### ISSUE TITLE
Question about first user login

### ISSUE THREAD

**Issue by meta0102** [Salman-Kashfy/Multitenancy-AdonisJS-5#1]
Hi, thank you for this repo. I think i understood everything how you implemented multi tenants.
What i'm missing is how the first user login will work?
e.g user1 from tenant1 try to login the first time how does the authentication work? On the first login i cant add simpill_public_key to the header as i dont know to which tenant the user belongs to on login time.
As i asume the tenants users are only stored in the tenant table and not in the landlord tabel.
Thanks you

**Comment by Salman-Kashfy** [comment]
The first user needs to be the product owner, add user with role admin in
landlord service

**Comment by Salman-Kashfy** [comment]
You will have to create a service in landlord for tenant registration, in business POV, tenants requests must be verified by landlord(admin or product owner), On acceptance of tenant requests by admin, generate a new database and new key `simpill_public_key` and store database name and `simpill_public_key` in landlord `tenants` table. Now, tenants can use application services as long as their users add key in request header, the `SwitchTenant` middleware will do all the job.

**Comment by meta0102** [comment]
Thank you for your fast response.
I'm thinking about having single users and tenants (companies) mixed. Would i it be a good approuch that companies can access with their own subdomain e.g tenant1.myapp.com on the frontend and based on that i add the simpill_public_key to the request header?

And for single users i maybe add a tenant named default where i store all single, none tenant users?

Thank you so much

**Comment by Salman-Kashfy** [comment]
> Thank you for your fast response. I'm thinking about having single users and tenants (companies) mixed. Would i it be a good approuch that companies can access with their own subdomain e.g tenant1.myapp.com on the frontend and based on that i add the simpill_public_key to the request header?
> 
> And for single users i maybe add a tenant named default where i store all single, none tenant users?
> 
> Thank you so much

Yes that is a good approach. That's exactly how SAAS products works e.g JIRA, workplace etc. Go for it. Just make sure users mention `simpill_public_key` in headers so the middleware `SwitchTenant` knows which database to look for. For your other question for single user, you can register users that will be your own users, but no need to add them to your tenants, keep them in landlord table and don't use `SwitchTenant` middleware for your user requsts, as you don't need a database switch for this case and default db connection is landlord.
